version: '3'

services:
  user-service:
    build:
      context: ./user_service
    ports:
      - "8001:8001"
  
  post-service:
    build:
      context: ./post_service
    ports:
      - "8002:8002"
  
  follow-service:
    build:
      context: ./follow_service
    ports:
      - "8003:8003"
  
  notification-service:
    build:
      context: ./notification_service
    ports:
      - "8004:8004"
