# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: notification-service
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: notification-service
#   template:
#     metadata:
#       labels:
#         app: notification-service
#     spec:
#       containers:
#       - name: notification-service
#         image: bhavesh9876/notification-service:latest  # Replace with your Docker image
#         ports:
#         - containerPort: 8001  # Change the internal port to 8001 for notification service
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: notification-service
# spec:
#   type: NodePort
#   ports:
#   - port: 8001       # Port within the Kubernetes cluster
#     targetPort: 8001  # The target port inside the container for this service
#     nodePort: 30003   # External port on the host for this service (can be adjusted)
#   selector:
#     app: notification-service


apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2  # Number of replicas for redundancy
  selector:
    matchLabels:
      app: notification-service  # Match pods with 'app: notification-service' label
  template:
    metadata:
      labels:
        app: notification-service  # Label the pods as 'app: notification-service'
    spec:
      containers:
      - name: notification-service  # Name of the container
        image: bhavesh9876/notification-service:latest  # Replace with the actual Docker image name
        ports:
        - containerPort: 8001  # Port where the notification service is running inside the container

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service  # Name of the service
spec:
  type: NodePort  # Expose the service externally via NodePort
  ports:
  - port: 8001         # Port exposed within the Kubernetes cluster
    targetPort: 8001   # Target port inside the container
    nodePort: 31001    # External NodePort for accessing the service (adjusted to avoid conflict)
  selector:
    app: notification-service  # Route traffic to pods with the 'app: notification-service' label

