apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: bhavesh9876/notification-service:latest  # Replace with your Docker image
        ports:
        - containerPort: 8001  # Change the internal port to 8001 for notification service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: NodePort
  ports:
  - port: 8001       # Port within the Kubernetes cluster
    targetPort: 8001  # The target port inside the container for this service
    nodePort: 30003   # External port on the host for this service (can be adjusted)
  selector:
    app: notification-service
