# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: user-service
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: user-service
#   template:
#     metadata:
#       labels:
#         app: user-service
#     spec:
#       containers:
#       - name: user-service
#         image: bhavesh9876/user-service:latest
#         ports:
#         - containerPort: 8001
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: user-service
# spec:
#   type: NodePort
#   ports:
#   - port: 8001
#     targetPort: 8001
#     nodePort: 30001
#   selector:
#     app: user-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: bhavesh9876/user-service:latest
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  ports:
  - port: 8001       # Port exposed inside the Kubernetes cluster
    targetPort: 8001  # Port the container listens on
    nodePort: 30001   # Port exposed outside of the cluster for accessing service
  selector:
    app: user-service
